<?php
$table = "CREATE TABLE db_user (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
sandi VARCHAR(50) NOT NULL,
alamat VARCHAR(255) ,
tlpn VARCHAR(50),
bagian VARCHAR(50),
dept VARCHAR(50),
posisi VARCHAR(50),
akses VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)";
